"""Alomatlar bo‘limlari — frontend bilan bir xil kalitlar (general, head, ...)."""

SYMPTOMS_BY_CATEGORY: dict[str, list[str]] = {
    "general": [
        "isitma",
        "charchoq",
        "zaiflik",
        "ishtahasizlik",
        "terlash",
        "titroq",
        "vazn yo'qotish",
        "qizish",
        "oq qon",
        "leykoz",
        "limfa bezlari",
        "burundan qon",
        "fever",
        "fatigue",
        "weakness",
        "chills",
    ],
    "head": [
        "bosh og'riq",
        "bosh aylanishi",
        "ko'z og'riq",
        "quloq og'riq",
        "burun bitishi",
        "burundan qon",
        "tish og'riq",
        "bo'yin og'riq",
        "headache",
        "dizziness",
        "earache",
        "nosebleed",
    ],
    "respiratory": [
        "yo'tal",
        "nafas qisishi",
        "ko'krak og'rig'i",
        "xirildash",
        "tomoq og'riq",
        "burun oqishi",
        "qichqiriq",
        "cough",
        "shortness of breath",
        "chest pain",
        "wheezing",
        "sore throat",
        "runny nose",
        "sneezing",
    ],
    "digestive": [
        "qorin og'riq",
        "ko'ngil aynish",
        "qayt qilish",
        "diareya",
        "qabziyat",
        "meteorizm",
        "o't qusish",
        "ishtaha yo'qligi",
        "abdominal pain",
        "nausea",
        "vomiting",
        "diarrhea",
        "constipation",
        "bloating",
        "heartburn",
    ],
    "musculoskeletal": [
        "bo'g'im og'riq",
        "mushak og'rig'i",
        "orqa og'riq",
        "bo'yin og'riq",
        "oyoq og'riq",
        "qo'l og'riq",
        "shish",
        "qotib qolish",
        "joint pain",
        "muscle pain",
        "back pain",
        "swelling",
        "stiffness",
    ],
    "skin": [
        "toshmalar",
        "qichishish",
        "ko'karishlar",
        "yara",
        "teri quruqligi",
        "ko'pchish",
        "teri sariqlik",
        "rash",
        "itching",
        "bruising",
        "wound",
        "dry skin",
        "swelling",
        "jaundice",
    ],
    "neurological": [
        "uyqu buzilishi",
        "xotira yo'qolishi",
        "epilepsia",
        "uyushish",
        "titroq",
        "muvozanat yo'qolishi",
        "insomnia",
        "memory loss",
        "numbness",
        "tremor",
        "balance problems",
        "confusion",
    ],
}

VALID_SYMPTOM_CATEGORY = frozenset(SYMPTOMS_BY_CATEGORY.keys())
